Project: Weather Data Analyzer  
This dataset contains daily Delhi weather data from 2013 to 2024, which is already cleaned and ready for analysis. It includes:

* Temperature
* Humidity
* Rainfall
* Wind speed
* Pressure
* Weather conditions

You can download it here:
https://www.kaggle.com/datasets/yug201/daily-climate-time-series-data-delhi-india?utm_source=chatgpt.com  
Delhi Daily Climate Dataset on Kaggle￼

In [1]:
print("Phase 1")

Phase 1

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv('kaggel_weather_2013_to_2024.csv')
df.head()
df.drop(columns='Unnamed: 0',inplace=True)
df.head()

,DATE,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,humidity,precip,precipprob,...,year-2000,weekofyear,tempmax_humidity,tempmin_humidity,temp_humidity,feelslikemax_humidity,feelslikemin_humidity,feelslike_humidity,temp_range,heat_index
0,4/14/2013,37.7,23.1,28.7,35.4,23.1,28.1,39.7,2.0,100,...,13,15,1496.69,917.07,1139.39,1405.38,917.07,1115.57,14.6,147.178118
1,4/15/2013,37.5,21.1,28.6,35.3,21.1,28.0,41.7,0.0,0,...,13,16,1563.75,879.87,1192.62,1472.01,879.87,1167.60,16.4,151.731061
2,4/16/2013,40.1,21.9,31.7,37.5,21.9,30.4,30.7,0.0,0,...,13,16,1231.07,672.33,973.19,1151.25,672.33,933.28,18.2,118.211133
3,4/17/2013,36.4,21.0,29.9,34.0,21.0,28.5,27.4,0.0,0,...,13,16,997.36,575.40,819.26,931.60,575.40,780.90,15.4,113.320354
4,4/18/2013,37.5,21.7,30.6,35.2,21.7,29.2,23.7,0.0,0,...,13,16,888.75,514.29,725.22,834.24,514.29,692.04,15.8,101.407038

In [4]:
df.columns

Index(['DATE', 'tempmax', 'tempmin', 'temp', 'feelslikemax', 'feelslikemin',
       'feelslike', 'humidity', 'precip', 'precipprob', 'precipcover',
       'windspeed', 'sealevelpressure', 'conditions', 'Year', 'month',
       'dayofweek', 'dayofyear', 'year-2000', 'weekofyear', 'tempmax_humidity',
       'tempmin_humidity', 'temp_humidity', 'feelslikemax_humidity',
       'feelslikemin_humidity', 'feelslike_humidity', 'temp_range',
       'heat_index'],
      dtype='str')

In [5]:
df= df[['DATE','temp','precip','tempmax','tempmin']]
print(df.shape)
print(df.isna().sum())
print("Data is clean and ready to work with")
df

(3557, 5)
DATE       0
temp       0
precip     0
tempmax    0
tempmin    0
dtype: int64
Data is clean and ready to work with

            DATE  temp  precip  tempmax  tempmin
0      4/14/2013  28.7     2.0     37.7     23.1
1      4/15/2013  28.6     0.0     37.5     21.1
2      4/16/2013  31.7     0.0     40.1     21.9
3      4/17/2013  29.9     0.0     36.4     21.0
4      4/18/2013  30.6     0.0     37.5     21.7
...          ...   ...     ...      ...      ...
3552  11/26/2024  18.6     0.0     25.8     13.6
3553  11/27/2024  18.4     0.0     26.2     12.5
3554  11/28/2024  17.9     0.0     25.8     11.5
3555  11/29/2024  18.0     0.0     25.0     10.6
3556  11/30/2024  18.0     0.0     25.0     11.0

[3557 rows x 5 columns]

In [6]:
arr_date = df['DATE'].to_numpy()
arr_temp = df['temp'].to_numpy()
arr_temp_max = df['tempmax'].to_numpy()
arr_temp_min = df['tempmin'].to_numpy()
arr_prepcip = df['precip'].to_numpy()

In [7]:
print("Phase 2")
print("Average Temperature",np.mean(arr_temp))
print("Maximum Temperature",np.max(arr_temp_max))
print("Minimum Temperature",np.min(arr_temp_min))
print("Standard Devaition of the Temperature",np.std(arr_temp))
print("Median Temperature",np.median(arr_temp))

Phase 2
Average Temperature 25.403373629463033
Maximum Temperature 47.9
Minimum Temperature 2.0
Standard Devaition of the Temperature 7.324511045202419
Median Temperature 27.7

In [16]:
print("Phase 3 Temperature Analysis")
k = np.argmax(arr_temp_max)
print("Hottest Day",arr_date[k])
k = np.argmin(arr_temp_min)
print("Coldest Day",arr_date[k])

total = arr_date.shape[0]

no_above35 = np.sum(np.where(arr_temp_max>35,True,False))
percent_no_above35 = round((no_above35/total*100),2)
print("Days above 35 degree Celsius",percent_no_above35,"%")


no_below10 = np.sum(np.where(arr_temp_min<10,True,False))
percent_no_below10 = round((no_below10/total*100),2)
print("Days below 10 degree Celsius",percent_no_below10,"%")

list_of_days = np.argsort(arr_temp_max)
all_indexes = list_of_days[-1:-11:-1]
j = 1
for i in all_indexes:
    print(j,"Hottest Day",arr_date[i],arr_temp_max[i])
    j+=1

Phase 3 Temperature Analysis
Hottest Day 5/29/2024
Coldest Day 12/28/2014
Days above 35 degree Celsius 31.97 %
Days below 10 degree Celsius 12.96 %
1 Hottest Day 5/29/2024 47.9
2 Hottest Day 5/24/2013 47.7
3 Hottest Day 6/10/2019 47.0
4 Hottest Day 5/22/2013 46.2
5 Hottest Day 5/23/2013 46.1
6 Hottest Day 5/26/2018 46.0
7 Hottest Day 5/15/2017 46.0
8 Hottest Day 5/29/2018 46.0
9 Hottest Day 5/26/2015 46.0
10 Hottest Day 5/30/2024 46.0

In [ ]:
print("Phase 4: Rainfall Analysis")